---
title: '"v2.OPEX_Forecast.Rolling.Stock.Focus"'
author: "Jason Marshall"
date: "August 23, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libs, include=FALSE, echo=FALSE, include = FALSE}
library(forecast) #time series forecast
library(tidyquant)
library(timetk) #edit time serices objects
library(sweep) #tidy model outputs
library(tidyverse) #tidy data
library(broom) #tidy ts model outputs
library(timeDate) #edit ts objects
library(reshape2) #shape data
library(data.table) #shape data setDT
library(readr) #data inport
library(corrr)      # Tidy correlation tables and correlation plotting
library(cowplot)    # Multiple plots with plot_grid()
library(tseries) #adf.test
library(astsa) #lag plot
library(TSA)
#library(DataExplorer) #exploratory data analysis
#library(Hmisc)
#library(caret) #model building
library(quantreg) #quantile regression
```

```{r load expense data from above code chunk, echo=FALSE}
####################################################################################
expense.dataset <- read_csv("Y:/Sharepoint Projects/Jason Marshall/R_Projects/OPEX_Forecasting/Data/US.opex.test.full.csv")


#Filter closed, wholesale, terminal, DC divisions
expense.dataset <- expense.dataset %>% 
  filter(str_detect(Division, "Admin") == FALSE) %>% 
  filter(str_detect(Division, "Closed") == FALSE) %>%
  filter(str_detect(Division, "DC") == FALSE) %>%
  filter(str_detect(Division, "Distribution") == FALSE) %>%
  filter(str_detect(Division, "Wholesale") == FALSE) %>%
  filter(str_detect(Division, "Terminals") == FALSE) %>%
  filter(str_detect(Division, "Terminal") == FALSE)

#change strings to factors
expense.dataset <- expense.dataset %>% mutate_if(is.character, as.factor)

#unit test
#unique(expense.dataset$Division)
levels(expense.dataset$Division)

#summary check
summary(expense.dataset)

#fill NAs
#expense.dataset %>% filter(is.na(Amount))
expense.dataset$Amount <- replace_na(expense.dataset$Amount, 0)

#summary check
#expense.dataset %>% group_by(Division) %>% summarise(sum = sum(Amount))
#summary(expense.dataset)
```

```{r create time series object: US Country Level, echo=FALSE}
#subset down to US Total Sum
US.Total.Expense.Dataset <- expense.dataset %>%
  #group by US
  group_by(Date, Parent.Account, Geography) %>%
  #sum expense amounts
  summarise(Expense.Sum = sum(Amount))

summary(US.Total.Expense.Dataset)

#unit test
sum(expense.dataset$Amount) == sum(US.Total.Expense.Dataset$Expense.Sum)

#make wide version
US.Total.Expense.Dataset <- dcast(data.table::setDT(US.Total.Expense.Dataset), 
                                     formula = Date + Geography ~ Parent.Account,
                                     value.var = c("Expense.Sum"),
                                     fun.aggregate = sum)
#summary check
#summary(US.Total.Expense.Dataset)

#fill NAs 
#US.Total.Expense.Dataset[is.na(US.Total.Expense.Dataset)] <- 0

#sort oldest to newest
US.Total.Expense.Dataset <- US.Total.Expense.Dataset %>%
  arrange(Date)

#create ts object drop first two cols (non-numeric)
US.Total.Expense.Dataset.TS <- timetk::tk_xts(data = US.Total.Expense.Dataset,
                                              #drop Geography
                                              select = -c(Geography),
                                              date_var = Date)
#Unit Test
#summary(US.Total.Expense.Dataset.TS)
start(US.Total.Expense.Dataset.TS)
end(US.Total.Expense.Dataset.TS)

#drop other datasets to help with file size
rm(expense.dataset)
#rm(US.Total.Expense.Dataset)
```

```{r filter data set to just rolling stock, echo=FALSE}
US.Roll.Stock <- US.Total.Expense.Dataset[,c('Date', 'Geography', 'ROLLING_STOCK')]

#create ts object drop first two cols (non-numeric)
US.Roll.Stock.TS <- ts(data = US.Roll.Stock[,-c(1,2)], 
                                     start = c(2013,01), frequency = 12)

#cut data set down to 2014 to match sales data
US.Roll.Stock.TS <- window(US.Roll.Stock.TS, start = c(2014,1))

#US.Total.Expense.Dataset.roll.stock.TS
```

```{r add sales data, echo=FALSE}
US.Sales.Data <- read_csv("Y:/Sharepoint Projects/Jason Marshall/R_Projects/OPEX_Forecasting/Data/US_Region_Division_Added_Only_NA_Item_Sales_chopdown_test a557ef9eb.csv")

# #make unique col names
colsNamesShelf <-colnames(US.Sales.Data)
dataset_col_names <- make.names(colsNamesShelf, unique = TRUE)
colnames(US.Sales.Data) <- dataset_col_names

#edit date format 
US.Sales.Data$Invoice.Date <- as.Date(US.Sales.Data$Invoice.Date, format = '%B %d, %Y')

#change invoice date to last month of the year for monthly sum and join with expense data
US.Sales.Data$Invoice.Date <- timeLastDayInMonth(US.Sales.Data$Invoice.Date) 

#change to character to facilitate group_by below
US.Sales.Data$Invoice.Date <- as.character(US.Sales.Data$Invoice.Date)
```

```{r shape sales data, echo=FALSE}
#Sum net sales and total margin for US Total
US.Sales.Data <- US.Sales.Data %>%
  #Select Data
  dplyr::select(Invoice.Date, GL.Shelf, Net.Sales, Total.Margin) %>%
  dplyr::group_by(Invoice.Date, GL.Shelf) %>% 
  dplyr::summarise(Net.Sales = sum(Net.Sales), Total.Margin = sum(Total.Margin))
  
#unit test
sum(US.Sales.Data$Net.Sales) == sum(US.Sales.Data$Net.Sales)
sum(US.Sales.Data$Total.Margin) == sum(US.Sales.Data$Total.Margin)
```

```{r US Sales Time Series, echo=FALSE}
#convert us.sales.data.cutdown to date for sort
US.Sales.Data$Invoice.Date <- as.Date(US.Sales.Data$Invoice.Date)
#sort by date
US.Sales.Data$Invoice.Date <- sort(US.Sales.Data$Invoice.Date, decreasing = FALSE)

#create ts object
US.Sales.Data.TS <- US.Sales.Data %>%
  dplyr::select(Invoice.Date, GL.Shelf, Net.Sales, Total.Margin)

#create wide version of data
US.Sales.Data.wide.TS <- dcast(data = data.table::setDT(US.Sales.Data.TS), 
                                  formula = Invoice.Date ~ GL.Shelf,
                                  value.var = c('Net.Sales', 'Total.Margin'),
                                  fun.aggregate = sum) %>%
  #Net.Sales.Total
  mutate(Net.Sales_Total = (Net.Sales_APPL + Net.Sales_CHEM + Net.Sales_FERT + Net.Sales_OTHE + Net.Sales_SEED)) %>%
  #Total.Margin.Total
  mutate(Total.Margin_Total = (Total.Margin_APPL + Total.Margin_CHEM + Total.Margin_FERT + Total.Margin_OTHE + Total.Margin_SEED))

#convert to ts object
US.Sales.Data.wide.TS <- timetk::tk_ts_(US.Sales.Data.wide.TS, start = c(2014,1), frequency = 12)

#join ts objects
US.Sales.RollStock.TS <- ts.intersect(US.Roll.Stock.TS, US.Sales.Data.wide.TS)
```

##Time Series EDA
```{r plot variables against rolling stock, echo=FALSE}
cols <- colnames(US.Sales.RollStock.TS)
#cols[i]
for (i in 2:length(cols)){
  data.plot <- autoplot(US.Sales.RollStock.TS[,c(1,i)]) + 
    ggtitle(paste("Rolling Stock vs", cols[i], sep = " "))
  print(data.plot)
}
```

```{r Season Plot for each variable, include= FALSE, echo=FALSE}
cols <- colnames(US.Sales.RollStock.TS)

for (i in cols){
  data.plot <- ggseasonplot(US.Sales.RollStock.TS[,i]) +
    ggtitle(paste("Season Plot:", i, sep = " "))
  print(data.plot)
}
```

```{r sub Season Plot for each variable}
cols <- colnames(US.Sales.RollStock.TS)

for (i in cols){
  data.plot <- ggsubseriesplot(US.Sales.RollStock.TS[,i]) +
    ggtitle(paste("Subseries Plot:", i, sep = " "))
  
  print(data.plot)
}
```
```{r Box  Plot for each variable}
cols <- colnames(US.Sales.RollStock.TS)

for (i in cols){
  box.plot <- boxplot(US.Sales.RollStock.TS[,i] ~ cycle(US.Sales.RollStock.TS[,i]), 
                      main = paste("Box Plot:", i, sep = " "))
  print(box.plot)
  }
```

```{r ACF Plot}
cols <- colnames(US.Sales.RollStock.TS)

for (i in cols){
  acf.plot <- ggAcf(US.Sales.RollStock.TS[,i]) + 
    ggtitle(paste("ACF Plot:", i, " "))
  print(acf.plot)
}

#commentary: all variables display seasonal autocorrelation (peak a lag 12 months)
```

```{r ACF Plot seasonal dif}
cols <- colnames(US.Sales.RollStock.TS)

for (i in cols){
  acf.plot <- ggAcf(base::diff(US.Sales.RollStock.TS[,i], lag = 12)) + 
    ggtitle(paste("ACF Plot:", i, " "))
  print(acf.plot)
}

#commentary: all variables display seasonal autocorrelation (peak a lag 12 months)
```

```{r rolling stock to sales scatter plots}
cols <- colnames(US.Sales.RollStock.TS)
#cols
#i
  dataset.tbl <-  US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "margin.fert", "margin.other", "margin.seed", "total.sales", "total.marg"))
  
for (i in 2: length(cols)){
  #print(i)
  #print(colnames(US.Total.Expense.Dataset.roll.stock.xts[,i]))
  # dataset.tbl <-  US.Total.Expense.Dataset.roll.stock.xts %>%
  # timetk::tk_tbl() %>% 
  # setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
  #          "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg"))
  #set x y variables
  
  x <- dataset.tbl[,i]
  y <- dataset.tbl[,2]
  
  #create scatterplot for x/y variables 
  scatter.plot <- ggplot2::ggplot(dataset.tbl[,c(2,i)],
                                aes(x =x, y = y)) + 
    geom_point() +
    xlab(colnames(dataset.tbl[,i])) + 
    ylab(colnames(dataset.tbl[,2])) + 
    geom_smooth(method = 'lm') + 
    geom_smooth(method = 'loess', color = 'red')
  
    print(scatter.plot)
}
```

```{R correlations, echo = FALSE}
#colnames(US.Total.Expense.Dataset.roll.stock.xts)

 Correlations <- US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
           marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
  corrr::correlate() %>%
  select(rowname, roll.stock)
print(Correlations)

# #Network Plot
# US.Total.Expense.Dataset.roll.stock.xts %>%
#   timetk::tk_tbl() %>% 
#   setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
#            "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
#   dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
#            marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
#   corrr::correlate() %>%
#   network_plot(colours = c(palette_light()[[2]], "white", palette_light()[[4]]), legend = TRUE) +
#     # labs(
#     #     title = "Correlations of tidyverse Package Downloads to Total CRAN Downloads",
#     #     subtitle = "Looking at January through June, tidyquant is a clear outlier"
#     #     ) +
#     expand_limits(x = c(-0.75, 0.25), y = c(-0.4, 0.4)) +
#     theme_tq() +
#     theme(legend.position = "bottom")
```

```{r create tbl for rolling correlations}
US.Sales.RollStock.TBL <- US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  # dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
  #          marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
   #dplyr::select(index, roll.stock, sales.chem) %>%
  #mutation
  tq_mutate_xy(
    y = roll.stock,
    x = sales.chem,
    mutate_fun = runCor,
    n = 3,
    use = "pairwise.complete.obs",
    col_rename = "rolling_corr"
  )
```



```{r rolling correlations chem to roll.stock, echo=FALSE}
US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  # dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
  #          marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
   #dplyr::select(index, roll.stock, sales.fert) %>%
  #mutation
  tq_mutate_xy(
    y = roll.stock,
    x = sales.chem,
    mutate_fun = runCor,
    n = 3,
    use = "pairwise.complete.obs",
    col_rename = "rolling_corr"
  ) %>%
  ggplot(aes(x = index)) + 
  geom_line(aes(y = rolling_corr), color = "red") + 
  ggtitle("Rolling Correlations: Rolling Stock to sales.chem")

```

```{r rolling correlations fert to roll.stock, echo=FALSE}
US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  # dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
  #          marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
   #dplyr::select(index, roll.stock, sales.fert) %>%
  #mutation
  tq_mutate_xy(
    y = roll.stock,
    x = sales.fert,
    mutate_fun = runCor,
    n = 3,
    use = "pairwise.complete.obs",
    col_rename = "rolling_corr"
  ) %>%
  ggplot(aes(x = index)) + 
  geom_line(aes(y = rolling_corr), color = "red") + 
  ggtitle("Rolling Correlations: Rolling Stock to sales.fert")
```

```{r rolling correlations fert to roll.stock, echo=FALSE}
US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  # dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
  #          marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
   #dplyr::select(index, roll.stock, sales.fert) %>%
  #mutation
  tq_mutate_xy(
    y = roll.stock,
    x = sales.appl,
    mutate_fun = runCor,
    n = 3,
    use = "pairwise.complete.obs",
    col_rename = "rolling_corr"
  ) %>%
  ggplot(aes(x = index)) + 
  geom_line(aes(y = rolling_corr), color = "red") + 
  ggtitle("Rolling Correlations: Rolling Stock to sales.appl")
```

```{r rolling correlations fert to roll.stock, echo=FALSE}
US.Sales.RollStock.TS %>%
  timetk::tk_tbl() %>% 
  setNames(.,c("index", "roll.stock", "sales.appl", "sales.chem", "sales.fert", "sales.other", "sales.seed",
           "marg.appl", "marg.chem", "marg.fert", "marg.other", "marg.seed", "tot.sales", "tot.marg")) %>%
  # dplyr::select(roll.stock, sales.appl, sales.chem, sales.fert, sales.other, sales.seed,
  #          marg.appl, marg.chem, marg.fert, marg.other, marg.seed, tot.sales, tot.marg ) %>%
   #dplyr::select(index, roll.stock, sales.fert) %>%
  #mutation
  tq_mutate_xy(
    y = roll.stock,
    x = sales.seed,
    mutate_fun = runCor,
    n = 3,
    use = "pairwise.complete.obs",
    col_rename = "rolling_corr"
  ) %>%
  ggplot(aes(x = index)) + 
  geom_line(aes(y = rolling_corr), color = "red") + 
  ggtitle("Rolling Correlations: Rolling Stock to sales.seed")
```

```{r Cross Correlation Plot}

ggCcf(diff(US.Sales.RollStock.TS[,1], 12),
                    diff(US.Sales.RollStock.TS[,2], 12), type = "correlation", plot = TRUE)

data <- US.Sales.RollStock.TS[,c("roll.stock",i)]

cols <- colnames(US.Sales.RollStock.TBL[,-c(1,2)])

for (i in 3:length(cols)) {
  data <- US.Sales.RollStock.TS[,c(1,i)]
  
  ccf.plot <- ggCcf(diff(data[,1], 12),
                    diff(data[,2], 12)) + 
                      ggtitle(paste(colnames(data[,1]), colnames(data[,2]), sep = " "))
  print(ccf.plot)
}

```

```{r ARIMA model Test no external variables}
model <- auto.arima(US.Sales.RollStock.TS[,1], D = 1, 
                      approximation = FALSE, 
                      stepwise = FALSE, seasonal = TRUE)
#glance(model)

model
summary(model)

fcast.model <- forecast(model, h = 12)

plot <- autoplot(fcast.model, series="Forecast") +
    autolayer(model$fitted, series="Forecast Model") +
    autolayer(US.Sales.RollStock.TS[,1], series = "Actuals") + 
    xlab("Year") + 
    ylab("Actuals") +
    ggtitle(paste("ARIMA Forecast ROlling Stock Test Sales ExtVars", i, sep = " "))
  
print(plot)

checkresiduals(model)
```

```{r external variable test no lag}
#models sales variable
xreg.model <- auto.arima(US.Sales.RollStock.TS[,12], D = 1, 
                      approximation = FALSE, 
                      stepwise = FALSE, seasonal = TRUE)

xreg.fcast.model <- forecast(xreg.model, h = 12)

plot <- autoplot(xreg.fcast.model, series="Forecast") +
    autolayer(xreg.model$fitted, series="Forecast Model") +
    autolayer(US.Sales.RollStock.TS[,12], series = "Actuals") + 
    xlab("Year") + 
    ylab("Actuals") +
    ggtitle(paste("ARIMA Forecast Sales ExtVars", i, sep = " "))
  
print(plot)

checkresiduals(xreg.model)

#model external variables
model <- auto.arima(US.Sales.RollStock.TS[,1], D = 1, 
                      approximation = FALSE, 
                      stepwise = FALSE, seasonal = TRUE, 
                    xreg = US.Sales.RollStock.TS[,12])

model
summary(model)

fcast.model <- forecast(model, h = 12, xreg = xreg.fcast.model$mean)

plot <- autoplot(fcast.model, series="Forecast") +
    autolayer(model$fitted, series="Forecast Model") +
    autolayer(US.Sales.RollStock.TS[,1], series = "Actuals") + 
    xlab("Year") + 
    ylab("Actuals") +
    ggtitle(paste("ARIMA Forecast ROlling Stock Test Sales ExtVars", i, sep = " "))
  
print(plot)

checkresiduals(model)
```

```{r external variable test 1 lag}
#models sales variable
xreg.model <- auto.arima(US.Sales.RollStock.TS[,12], D = 1, 
                      approximation = FALSE, 
                      stepwise = FALSE, seasonal = TRUE)

xreg.fcast.model <- forecast(xreg.model, h = 12)

plot <- autoplot(xreg.fcast.model, series="Forecast") +
    autolayer(xreg.model$fitted, series="Forecast Model") +
    autolayer(US.Sales.RollStock.TS[,12], series = "Actuals") + 
    xlab("Year") + 
    ylab("Actuals") +
    ggtitle(paste("ARIMA Forecast Sales ExtVars", i, sep = " "))
  
print(plot)

checkresiduals(xreg.model)

#model external variables
model <- auto.arima(US.Sales.RollStock.TS[,1], D = 1, 
                      approximation = FALSE, 
                      stepwise = FALSE, seasonal = TRUE, 
                    xreg = stats::lag(US.Sales.RollStock.TS[,12], k = 1))

model
summary(model)

fcast.model <- forecast(model, h = 12, xreg = xreg.fcast.model$mean)

plot <- autoplot(fcast.model, series="Forecast") +
    autolayer(model$fitted, series="Forecast Model") +
    autolayer(US.Sales.RollStock.TS[,1], series = "Actuals") + 
    xlab("Year") + 
    ylab("Actuals") +
    ggtitle(paste("ARIMA Forecast ROlling Stock Test Sales ExtVars", i, sep = " "))
  
print(plot)

checkresiduals(model)
```
